plugins {
    id 'com.android.application'
}
android {
    namespace 'com.setsail.bilifiddler'
    compileSdk 34
    defaultConfig {
        applicationId "com.setsail.bilifiddler"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        release {
            storeFile file('sign/bili.keystore')
            storePassword 'bilifiddler'
            keyAlias 'bili'
            keyPassword 'bilifiddler'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
